# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: azureml-unit-tests

on:
  pull_request:
    branches:
      - 'staging'
      - 'main'
    paths:
      # Tests will be run only when there are changes in the code:
      - examples/**
      - '!examples/**/*.md'
      - recommenders/**
      - '!recommenders/**/*.md'
      - tests/**
      - '!tests/**/*.md'
      - setup.py

  # Enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: 'Tags to label this manual run (optional)'
        default: 'Manual trigger'

  # Make this workflow reusable
  workflow_call:

jobs:
  get-test-groups:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get test group names
        id: get_test_groups
        uses: ./.github/actions/get-test-groups
        with:
          TEST_KIND: "unit"
      - name: Print test group names
        run: echo ${{ steps.get_test_groups.outputs.test_groups }}
        shell: bash
    outputs:
      test_groups: ${{ steps.get_test_groups.outputs.test_groups }}

  execute-tests:
    needs: get-test-groups
    name: ${{ join(matrix.*, ', ') }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 50 # Usage limits: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
      matrix:
        python-version: ['"python=3.8"', '"python=3.9"']
        test-group:  ${{ fromJSON(needs.get-test-groups.outputs.test_groups) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Execute tests
        uses: ./.github/actions/azureml-test
        id: execute_tests
        with:
          EXP_NAME: 'unit_tests'
          TEST_KIND: 'unit'
          AZUREML_TEST_CREDENTIALS: ${{ secrets.AZUREML_TEST_CREDENTIALS }}
          AZUREML_TEST_SUBID: ${{ secrets.AZUREML_TEST_SUBID }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          TEST_GROUP: ${{ matrix.test-group }}
